export enum HttpStatus {
    user_not_active = 800,
    user_not_exists = 801,
    username_not_exists = 802,
    password_incorrect = 803,
    authentication_failed = 804,
    authentication_ok = 805,
    username_exists = 806,
    user_created_failed = 807,
    user_created = 808,
    activation_notification = 809,
    activation_notification_failed = 810,
    reset_password_notification = 811,
    reset_password_notification_failed = 812,
    password_changed = 813,
    password_changed_failded = 814,
    email_not_exists = 815,
    reset_password_key_not_exists = 816,
    activation_failed = 817,
    activation_ok = 818
}